moonstar0331/fintech-loan

src/main/java/com/loan/loan/controller/CounselController.java, src/main/java/com/loan/loan/service/CounselService.java, src/main/java/com/loan/loan/service/CounselServiceImpl.java, src/test/java/com/loan/loan/service/CounselServiceTest.java
대출 상담 조회 기능을 구현하고 비즈니스 로직에 대한 테스트케이스를 작성하였다.
=> Feat: 대출 상담 조회 기능 구현

src/main/java/com/loan/loan/controller/CounselController.java, src/main/java/com/loan/loan/service/CounselService.java, src/main/java/com/loan/loan/service/CounselServiceImpl.java, src/test/java/com/loan/loan/service/CounselServiceTest.java
대출 상담 정보 수정 기능에 대해서 구현하였으며, 수정 기능의 비즈니스 로직에 대한 테스트케이스를 작성하였다.
=> Feat: 대출 상담 정보 수정 기능 구현

src/main/java/com/loan/loan/domain/Application.java
대출 신청 기능을 구현하기 위한 대출 신청 Application 도메인 테이블을 정의하였다.
=> Feat: 대출 신청 도메인 테이블 정의

src/main/java/com/loan/loan/controller/ApplicationController.java, src/main/java/com/loan/loan/dto/ApplicationDTO.java, src/main/java/com/loan/loan/dto/CounselDTO.java, src/main/java/com/loan/loan/repository/ApplicationRepository.java, src/main/java/com/loan/loan/service/ApplicationService.java, src/main/java/com/loan/loan/service/ApplicationServiceImpl.java, src/test/java/com/loan/loan/service/ApplicationServiceTest.java
대출 신청을 등록하기 위한 기능을 구현하고 그에 맞는 도메인을 함께 작성하였다.
추가적으로 대출 신청 등록 기능에서 필요한 비즈니스 로직에 대한 유닛 테스트도 함께 작성하였다.
=> Feat: 대출 신청 등록 기능 구현

src/main/java/com/loan/loan/controller/ApplicationController.java, src/main/java/com/loan/loan/service/ApplicationService.java, src/main/java/com/loan/loan/service/ApplicationServiceImpl.java, src/test/java/com/loan/loan/service/ApplicationServiceTest.java
대출 신청 조회 기능을 구현하고, 대출 신청 내역을 조회하는 비즈니스 로직에 대한 테스트케이스를 작성하였다.
=> Feat: 대출 신청 조회 기능 구현

src/main/java/com/loan/loan/controller/ApplicationController.java, src/main/java/com/loan/loan/service/ApplicationService.java, src/main/java/com/loan/loan/service/ApplicationServiceImpl.java, src/test/java/com/loan/loan/service/ApplicationServiceTest.java
신청한 대출에 대한 삭제 기능에 대해서 구현하고 삭제 기능을 위한 비즈니스 로직에 대한 테스트케이스를 함께 작성하였다.
=> Feat: 대출 신청 삭제 기능 구현

src/main/java/com/loan/loan/controller/ApplicationController.java, src/main/java/com/loan/loan/domain/Application.java, src/main/java/com/loan/loan/dto/ApplicationDTO.java, src/main/java/com/loan/loan/repository/ApplicationRepository.java, src/main/java/com/loan/loan/service/ApplicationService.java, src/main/java/com/loan/loan/service/ApplicationServiceImpl.java, src/test/java/com/loan/loan/service/ApplicationServiceTest.java
대출 신청과 관련된 CRUD 기능에 대한 구현하고, 각 CRUD를 위한 비즈니스 로직에 대한 테스트케이스를 함께 작성하였다.
=> Feat: 대출 신청 CRUD 구현

src/main/java/com/loan/loan/domain/Terms.java
대출 신청을 위한 이용 약관에 대한 도메인 테이블을 작성하였다.
=> Feat: 이용 약관 도메인 테이블 작성

src/main/java/com/loan/loan/controller/CounselController.java, src/main/java/com/loan/loan/controller/TermsController.java, src/main/java/com/loan/loan/dto/TermsDTO.java, src/main/java/com/loan/loan/repository/TermsRepository.java, src/main/java/com/loan/loan/service/TermsService.java, src/main/java/com/loan/loan/service/TermsServiceImpl.java, src/test/java/com/loan/loan/service/TermsServiceTest.java
이용 약관과 관련된 도메인 테이블을 정의하고 이용 약관 등록 기능을 구현하였다.
추가적으로 이용 약관 등록 기능의 비즈니스 로직에 대한 테스트케이스를 작성하였다.
=> Feat : 이용 약관 등록 기능 구현

src/main/java/com/loan/loan/controller/TermsController.java, src/main/java/com/loan/loan/service/TermsService.java, src/main/java/com/loan/loan/service/TermsServiceImpl.java, src/test/java/com/loan/loan/service/TermsServiceTest.java
등록된 이용 약관의 전체를 조회하는 기능을 구현하고, 추가적으로 이용 약관 전체 조회의 비즈니스 로직에 대해서 테스트케이스를 작성하였다.
=> Feat : 이용 약관 전체 조회 기능 구현

src/main/java/com/loan/loan/controller/ApplicationController.java, src/main/java/com/loan/loan/domain/AcceptTerms.java, src/main/java/com/loan/loan/dto/ApplicationDTO.java, src/main/java/com/loan/loan/repository/AcceptTermsRepository.java, src/main/java/com/loan/loan/service/ApplicationService.java, src/main/java/com/loan/loan/service/ApplicationServiceImpl.java, src/test/java/com/loan/loan/service/ApplicationServiceTest.java
고객이 대출 신청 시에 약관 동의하는 기능에 대해서 구현하고, 약관 동의 시에 대출과 약관에 대한 validation 을 하였다.
추가적으로 대출 신청 약관 동의 기능의 비즈니스 로직에 대한 테스트케이스를 작성하였다.
=> Feat : 대출 신청 약관 동의 기능 구현

src/main/java/com/loan/loan/controller/ApplicationController.java, src/main/java/com/loan/loan/service/FileStorageService.java, src/main/java/com/loan/loan/service/FileStorageServiceImpl.java, src/main/resources/application.yml
대출 신청시 작성하는 서류를 등록하는 기능은 임시로 구현하였다.
=> Feat : 대출 신청 서류 등록 기능 구현

src/main/java/com/loan/loan/controller/ApplicationController.java, src/main/java/com/loan/loan/dto/FileDTO.java, src/main/java/com/loan/loan/exception/ResultType.java, src/main/java/com/loan/loan/service/FileStorageService.java, src/main/java/com/loan/loan/service/FileStorageServiceImpl.java
업로드한 대출 신청 서류를 관리하는 기능을 구현하였다.
* 파일 업로드
* 하나의 파일 다운로드 기능
* 파일 정보 리스트 조회 기능
=> Feat : 대출 신청 서류 조회 기능 구현

src/main/java/com/loan/loan/controller/ApplicationController.java, src/main/java/com/loan/loan/service/FileStorageService.java, src/main/java/com/loan/loan/service/FileStorageServiceImpl.java
지정된 경로에 존재하는 모든 파일들을 삭제하는 기능을 구현하였다.
=> Feat : 대출 신청 서류 삭제 기능 구현

src/main/java/com/loan/loan/controller/ApplicationController.java, src/main/java/com/loan/loan/service/FileStorageService.java, src/main/java/com/loan/loan/service/FileStorageServiceImpl.java
기존의 코드에서는 대출과 신청 서류 사이의 매핑을 생각하지 않고 신청 서류와 관련된 기능들을 구현하였다. 이에 신청하는 대출과 신청 서류 사이의 매핑이 되도록 구현을 하였다.
=> Feat: 대출 신청 서류 매핑 기능 구현

src/main/java/com/loan/loan/controller/ApplicationController.java, src/main/java/com/loan/loan/dto/FileDTO.java, src/main/java/com/loan/loan/exception/ResultType.java, src/main/java/com/loan/loan/service/FileStorageService.java, src/main/java/com/loan/loan/service/FileStorageServiceImpl.java, src/main/resources/application.yml
대출 신청 시에 신청 서류를 관리하는 기능을 구현하였다.
* 대출 신청 서류 등록 기능 구현
* 대출 신청 서류 조회 기능 구현
* 대출 신청 서류 삭제 기능 구현
* 대출과 신청 서류 매핑
=> Feat : 대출 신청 서류 기능 구현

src/main/java/com/loan/loan/domain/Application.java, src/main/java/com/loan/loan/domain/Judgment.java
고객이 신청한 대출 신청에 대해서 심사하는 기능을 위한 'Judgment' 테이블을 정의하고
대출 신청에 대해서 심사에서 승인된 금액을 나타내는 속성을 추가하였다.
=> Feat: 대출 심사 도메인 테이블 정의 및 대출 신청 도메인 테이블 수정

src/main/java/com/loan/loan/controller/JudgementController.java, src/main/java/com/loan/loan/dto/JudgmentDTO.java, src/main/java/com/loan/loan/repository/JudgementRepository.java, src/main/java/com/loan/loan/service/JudgementServiceImpl.java, src/main/java/com/loan/loan/service/JudgmentService.java, src/test/java/com/loan/loan/service/JudgementServiceTest.java
고객이 신청한 대출 건에 대해서 심사를 등록하는 기능을 구현하고, 
추가적으로 대출 심사 등록 기능의 비즈니스 로직에 대한 테스트케이스를 작성하였다.
=> Feat : 대출 심사 등록 기능 구현

src/main/java/com/loan/loan/controller/JudgementController.java, src/main/java/com/loan/loan/dto/ApplicationDTO.java, src/main/java/com/loan/loan/service/JudgementServiceImpl.java, src/main/java/com/loan/loan/service/JudgmentService.java, src/test/java/com/loan/loan/service/JudgementServiceTest.java
고객이 등록한 대출 신청에 대해서 진행한 대출 심사에서 승인된 금액을 부여하는 기능을 구현하고,
추가적으로 대출 심사 금액 부여 기능의 비즈니스 로직에 대한 테스트케이스를 작성하였다.
=> Feat : 대출 심사 금액 부여 기능 구현

src/main/java/com/loan/loan/controller/JudgementController.java, src/main/java/com/loan/loan/domain/Application.java, src/main/java/com/loan/loan/domain/Judgment.java, src/main/java/com/loan/loan/dto/ApplicationDTO.java, src/main/java/com/loan/loan/dto/JudgmentDTO.java, src/main/java/com/loan/loan/repository/JudgementRepository.java, src/main/java/com/loan/loan/service/JudgementServiceImpl.java, src/main/java/com/loan/loan/service/JudgmentService.java, src/test/java/com/loan/loan/service/JudgementServiceTest.java
고객이 등록한 대출 신청에 대해서 진행하는 대출 심사와 관련된 기능을 구현하였다.
* 대출 심사 도메인 테이블 정의
* 대출 심사 등록 기능 구현
* 대출 심사 정보 조회 기능 구현
* 대출 심사 정보 수정 기능 구현 (구현된 DTO 만을 사용하기 위해 간단하게 구현)
* 대출 심사 정보 삭제 기능 구현
* 고객이 등록한 대출 신청에 대해서 진행한 대출 심사 결과로 승인된 금액 대출 신청 정보에 적용 기능
* 대출 심사와 관련된 기능들의 비즈니스 로직에 대한 테스트케이스 작성
=> Feat : 대출 심사 기능 개발

src/main/java/com/loan/loan/controller/ApplicationController.java, src/main/java/com/loan/loan/domain/Application.java, src/main/java/com/loan/loan/dto/ApplicationDTO.java, src/main/java/com/loan/loan/service/ApplicationService.java, src/main/java/com/loan/loan/service/ApplicationServiceImpl.java
고객이 등록한 대출 신청에 대해서 심사 후 대출 계약 체결 기능을 구현하였다.
=> Feat : 대출 계약 기능 구현

src/main/java/com/loan/loan/controller/ApplicationController.java, src/main/java/com/loan/loan/controller/InternalController.java, src/main/java/com/loan/loan/domain/Application.java, src/main/java/com/loan/loan/domain/Balance.java, src/main/java/com/loan/loan/domain/Entry.java, src/main/java/com/loan/loan/dto/ApplicationDTO.java, src/main/java/com/loan/loan/dto/BalanceDTO.java, src/main/java/com/loan/loan/dto/EntryDTO.java, src/main/java/com/loan/loan/repository/BalanceRepository.java, src/main/java/com/loan/loan/repository/EntryRepository.java, src/main/java/com/loan/loan/service/ApplicationService.java, src/main/java/com/loan/loan/service/ApplicationServiceImpl.java, src/main/java/com/loan/loan/service/BalanceService.java, src/main/java/com/loan/loan/service/BalanceServiceImpl.java, src/main/java/com/loan/loan/service/EntryService.java, src/main/java/com/loan/loan/service/EntryServiceImpl.java
대출 계약 후에 내부에서 대출을 집행하는 기능에 대해서 CRUD 위주로 개발하였다.
=> Feat : 대출 집행 기능 개발

src/main/java/com/loan/loan/domain/Repayment.java
대출 상환 기능을 구현하기 위해서 대출 상환에 대한 도메인 테이블을 정의하였다.
=> Feat: 대출 상환 도메인 테이블 정의

src/main/java/com/loan/loan/controller/InternalController.java, src/main/java/com/loan/loan/dto/BalanceDTO.java, src/main/java/com/loan/loan/dto/RepaymentDTO.java, src/main/java/com/loan/loan/repository/RepaymentRepository.java, src/main/java/com/loan/loan/service/BalanceService.java, src/main/java/com/loan/loan/service/BalanceServiceImpl.java, src/main/java/com/loan/loan/service/RepaymentService.java, src/main/java/com/loan/loan/service/RepaymentServiceImpl.java
대출 상환을 등록하는 기능을 구현하였다.
대출 상환에 대해서 구현하기 위해서 기존에 존재하는 대출 잔고에 대해서
대출 상환 시에 대출 잔고의 내역이 수정되는 로직을 함께 작성해주었다.
잔고의 수정은 대출을 상환 시에 잔여 대출 잔고가 줄어드는 경우와
대출 잔고가 롤백이 되는 경우를 함께 구현해주었다.
=> Feat : 대출 상환 등록 기능 구현

src/main/java/com/loan/loan/controller/InternalController.java, src/main/java/com/loan/loan/dto/RepaymentDTO.java, src/main/java/com/loan/loan/repository/RepaymentRepository.java, src/main/java/com/loan/loan/service/RepaymentService.java, src/main/java/com/loan/loan/service/RepaymentServiceImpl.java
등록되어 있는 대출에 대해서 대출 상환에 대한 전체 내역을 조회하는 기능을 구현하였다.
전체 내역을 조회하는 것이기 때문에 Response DTO 에서 중복된 내역이 들어가지 않도록
ListResponse 라는 이름으로 Response DTO 를 새롭게 정의해 주었다.
=> Feat : 대출 상환 전체 조회 기능 구현

src/main/java/com/loan/loan/controller/InternalController.java, src/main/java/com/loan/loan/service/RepaymentService.java, src/main/java/com/loan/loan/service/RepaymentServiceImpl.java
등록한 대출 상환 내역에 대해서 삭제하는 기능을 구현하였다.
대출 상환을 등록하면서 대출 잔고가 줄어들었기 때문에 기존에 작성한 대출 잔고 수정 기능을 통해서
대출 잔고를 롤백시키면서 등록된 대출 상환 내역이 삭제되도록 구현하였다.
=> Feat : 대출 상환 삭제 기능 구현

src/main/java/com/loan/loan/controller/InternalController.java, src/main/java/com/loan/loan/domain/Repayment.java, src/main/java/com/loan/loan/dto/BalanceDTO.java, src/main/java/com/loan/loan/dto/RepaymentDTO.java, src/main/java/com/loan/loan/repository/RepaymentRepository.java, src/main/java/com/loan/loan/service/BalanceService.java, src/main/java/com/loan/loan/service/BalanceServiceImpl.java, src/main/java/com/loan/loan/service/RepaymentService.java, src/main/java/com/loan/loan/service/RepaymentServiceImpl.java
대출 상환 관련된 기능을 구현하였다.
* 대출 상환 등록 기능 개발
* 대출 상환 전체 조회 기능 개발
* 대출 상환 수정 기능 개발
* 대출 상환 삭제 기능 개발
위의 기능들을 구현하기 위해서 추가적으로 등록된 대출 내역의 대출 잔고를 함께 수정하는 로직을 구현하였다.
=> Feat : 대출 상환 기능 개발
